[
  "\nif __name__ == \"__main__\":\n    main()",

  "\nimport ast\n\nimport re\n\nFUNC_PATTERN = re.compile(r'^\\s*(def|function|func|fn)\\s+(\\w+)', re.MULTILINE)\n\n\nfrom hashing import hash_chunk\n\n",
  
  "from embedder import Embedder\n\nif __name__ == \"__main__\":\n    print(\"Starting the embedder...\")\n    embedder = Embedder()\n    print(f\"Embedder initialized with model: {embedder.model_name}\")",
  
  "    def _extract_module_level_chunks(self, filepath: str, tree: ast.Module, lines: list[str]) -> list[Chunk]:\n        # Only look at TOP-LEVEL statements (tree.body), not nested ones —\n        # nested module-level code inside functions is already part of that function's chunk.\n        top_level_func_class_lines = set()\n        for node in tree.body:\n            if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef, ast.ClassDef)):\n                start = node.lineno\n                if node.decorator_list:\n                    start = min(d.lineno for d in node.decorator_list)\n                top_level_func_class_lines.update(range(start, node.end_lineno + 1))\n\n        total_lines = len(lines)\n        leftover_line_nums = [\n            i for i in range(1, total_lines + 1)\n            if i not in top_level_func_class_lines\n        ]\n\n        if not leftover_line_nums:\n            return []\n\n        # group leftover lines into contiguous runs (handles blank-line gaps between them)\n        runs = []\n        run_start = leftover_line_nums[0]\n        prev = run_start\n        for ln in leftover_line_nums[1:]:\n            if ln != prev + 1:\n                runs.append((run_start, prev))\n                run_start = ln\n            prev = ln\n        runs.append((run_start, prev))\n\n        chunks = []\n        for i, (start, end) in enumerate(runs):\n            content = \"\".join(lines[start - 1: end])\n            if not content.strip():\n                continue  # skip pure-whitespace runs (e.g. blank line between imports and class)\n            name = \"__module__\" if i == 0 else f\"__module__{i}\"\n            chunks.append(Chunk(\n                id=f\"{filepath}::{name}\",\n                file=filepath, kind=\"module\", qualified_name=name,\n                content=content, start_line=start, end_line=end,\n                content_hash=hash_chunk(content),\n            ))\n        return chunks\n",
  
  "@dataclass\nclass Chunk:\n    id: str              # stable identity: \"path/to/file.py::ClassName.method_name\"\n    file: str             # relative path from target root\n    kind: str              # \"function\" | \"async_function\" | \"class\" | \"config\"\n    qualified_name: str      # \"ClassName.method_name\" or \"function_name\"\n    content: str               # exact source text of the chunk (decorators included)\n    start_line: int\n    end_line: int\n    content_hash: str\n"
]