export const ENDPOINTS = {
  FILES_LIST: "/api/fs/list",
  FILES_READ: "/api/fs/read",
  FILES_WRITE: "/api/fs/write",
  FILES_CREATE: "/api/fs/create",
  FILES_DELETE: "/api/fs/delete",
  FILES_RENAME: "/api/fs/rename",

  AGENT_STATUS: "/status",
  AGENT_FILES: "/files",
  AGENT_FILE_CHUNKS: "/file/chunks",
  AGENT_FILE_SOURCE: "/file",
  AGENT_CHUNKS: "/chunks",
  AGENT_EVENTS: "/events",
  AGENT_INDEX: "/index",
  AGENT_INDEX_PATH: "/index/path",
  AGENT_INDEX_FORGET: "/index/forget",
  AGENT_CONTEXT: "/context",
  AGENT_ASK: "/ask",
  AGENT_PATCH_PROPOSE: "/patch/propose",
  AGENT_PATCH_APPLY: "/patch/apply",
  AGENT_PATCH_LOOP: "/patch/loop",
  AGENT_CONVERSATIONS: "/conversations",
} as const;
